# Optimized Dockerfile for Coolify deployment (Generated by Claude)
# Multi-stage build: Stage 1 builds the jar from source, Stage 2 is the slim runtime image

# ---------- Stage 1: Build ----------
FROM maven:3.9-eclipse-temurin-25 AS build

WORKDIR /build

# Copy only pom.xml first so Maven dependencies get cached
# (Docker layer cache: dependencies are only re-downloaded when pom.xml changes)
COPY pom.xml .
RUN mvn -B dependency:go-offline

# Copy the rest of the source code and build
COPY src ./src
RUN mvn -B clean package -DskipTests

# ---------- Stage 2: Runtime ----------
FROM eclipse-temurin:25

# Non-root user for better security (the Java process shouldn't run as root)
RUN useradd --create-home --shell /bin/bash rettichlp-discord-bot

# Working directory
WORKDIR /workspace

# Copy the built jar from the build stage
# Adjust the filename if your <finalName> in pom.xml is different
COPY --from=build /build/target/rettichlp-discord-bot.jar /workspace/rettichlp-discord-bot.jar

# Fix ownership so the non-root user can execute the file
RUN chown -R rettichlp-discord-bot:rettichlp-discord-bot /workspace

# Switch to the non-root user
USER rettichlp-discord-bot

CMD ["java", "-jar", "rettichlp-discord-bot.jar"]
